# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "5d5c8002-789e-4319-81d1-a60f08a77996",
# META       "default_lakehouse_name": "greensky_v2_lakehouse",
# META       "default_lakehouse_workspace_id": "640876ea-6158-4ffd-8598-5eb210e088a0",
# META       "known_lakehouses": [
# META         {
# META           "id": "5d5c8002-789e-4319-81d1-a60f08a77996"
# META         }
# META       ]
# META     },
# META     "environment": {
# META       "environmentId": "cf70e84c-e5f3-9589-4218-88cc1ae7b47d",
# META       "workspaceId": "00000000-0000-0000-0000-000000000000"
# META     }
# META   }
# META }

# MARKDOWN ********************

# ### Load config and plume catalog:

# CELL ********************

%run 00_config

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ### Load the gold plume catalog:

# CELL ********************

import pandas as pd
import numpy as np

_catalog = spark.table("gold_plume_catalog")
# The catalog's own Spark schema, kept so the write below reuses it rather than letting Spark
# re-infer every column from pandas values.
CATALOG_SCHEMA = _catalog.schema
plumes = _catalog.toPandas()
print(f"Loaded {len(plumes)} plumes from gold_plume_catalog")
print(f"Columns: {list(plumes.columns)}")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ### Load the facility reference table:
#
# `ref_facilities` is generated by `01a_build_facility_topology` from `TOPOLOGY_SEED`. It
# used to be built here, either by scraping EPA Envirofacts or -- whenever that call failed,
# which was most of the time -- by laying a 0.5 degree grid of `PB_nnn` points across the
# BBOX and attributing plumes to grid squares.
#
# Both paths are retired. `dim_facility` is now the single facility master, so this notebook
# reads the table rather than writing it. **It must not write `ref_facilities`**: doing so
# would replace the generated topology rows with grid points on the next run.

# CELL ********************

permian_fac = spark.table("ref_facilities").toPandas()

required = ["facility_id", "facility_name", "facility_lat", "facility_lon"]
missing = [c for c in required if c not in permian_fac.columns]
assert not missing, (
    f"ref_facilities is missing {missing}. Run 01a_build_facility_topology to rebuild it."
)
assert len(permian_fac) > 0, "ref_facilities is empty -- run 01a_build_facility_topology first"

# The PB_nnn grid fallback used to land here whenever the EPA call failed. Grid points are
# not facilities, and attributing a plume to one produced a site id that meant nothing.
grid = permian_fac["facility_id"].astype(str).str.match(r"^PB_\d+$")
assert not grid.any(), (
    f"{int(grid.sum())} PB_nnn grid reference points found in ref_facilities -- the table was "
    "overwritten by the retired fallback. Rerun 01a_build_facility_topology."
)

print(f"Loaded {len(permian_fac)} facilities from ref_facilities")
print(f"Columns: {list(permian_fac.columns)}")

if "region_band" in permian_fac.columns:
    print("\nBand distribution:")
    for band, n in permian_fac["region_band"].value_counts().items():
        print(f"  {band:<12}{n:>5}")

if "in_detection_bbox" in permian_fac.columns:
    n_out = int((~permian_fac["in_detection_bbox"]).sum())
    print(f"\n{n_out} facilities sit outside the detection BBOX. They stay in the candidate")
    print("set on purpose, so a plume near an edge can still attribute across it.")

print()
print(permian_fac[required].head(10).to_string(index=False))

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ### Wind-aware probabilistic attribution:

# CELL ********************

def haversine_km(lat1, lon1, lat2, lon2):
    """Haversine distance in km."""
    R = 6371.0
    dlat = np.radians(lat2 - lat1)
    dlon = np.radians(lon2 - lon1)
    a = (np.sin(dlat/2)**2 +
         np.cos(np.radians(lat1)) * np.cos(np.radians(lat2)) * np.sin(dlon/2)**2)
    return R * 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

def compute_bearing(lat1, lon1, lat2, lon2):
    """Compute bearing from point 1 to point 2 in degrees (0-360)."""
    lat1_r, lat2_r = np.radians(lat1), np.radians(lat2)
    dlon_r = np.radians(lon2 - lon1)
    x = np.sin(dlon_r) * np.cos(lat2_r)
    y = (np.cos(lat1_r) * np.sin(lat2_r) -
         np.sin(lat1_r) * np.cos(lat2_r) * np.cos(dlon_r))
    bearing = np.degrees(np.arctan2(x, y))
    return bearing % 360

def angular_difference(a1, a2):
    """Smallest angular difference between two angles in degrees."""
    diff = abs(a1 - a2) % 360
    if diff > 180:
        diff = 360 - diff
    return diff

# Attribution parameters
search_radius_km = CONFIG["attribution_search_radius_km"]  # 30 km
wind_sigma_deg = CONFIG["attribution_wind_sigma_deg"]  # 30 degrees

fac_lats = permian_fac["facility_lat"].values
fac_lons = permian_fac["facility_lon"].values
fac_ids = permian_fac["facility_id"].values
fac_names = permian_fac["facility_name"].values

attribution_results = []

for _, plume in plumes.iterrows():
    plume_lat = plume["source_lat"]
    plume_lon = plume["source_lon"]
    plume_id = plume["plume_id"]

    # Get wind direction at plume (direction wind is blowing TO)
    # ERA5 u10/v10: u=eastward, v=northward
    # Wind blows FROM upwind direction
    if "U_eff_ms" in plume and plume["U_eff_ms"] > 0:
        # Wind direction the plume came from (upwind)
        # atan2(u, v) gives the direction wind is blowing TO
        # We need where it came FROM (add 180)
        wind_to_deg = np.degrees(np.arctan2(
            plume.get("era5_u10", 0) if "era5_u10" in plume.index else 0,
            plume.get("era5_v10", 0) if "era5_v10" in plume.index else 0
        )) % 360
        upwind_dir = (wind_to_deg + 180) % 360
    else:
        upwind_dir = None

    # Score each facility
    candidates = []
    for i in range(len(fac_lats)):
        dist = haversine_km(fac_lats[i], fac_lons[i], plume_lat, plume_lon)

        if dist > search_radius_km:
            continue

        # Distance weight (Gaussian, sigma = 15 km)
        w_dist = np.exp(-dist**2 / (2.0 * 15.0**2))

        # Wind-direction weight
        if upwind_dir is not None:
            # Bearing from facility to plume
            bearing = compute_bearing(fac_lats[i], fac_lons[i], plume_lat, plume_lon)
            # Is the facility upwind of the plume?
            theta = angular_difference(bearing, upwind_dir)
            w_wind = np.exp(-theta**2 / (2.0 * wind_sigma_deg**2))
        else:
            w_wind = 1.0  # no wind info, equal weight

        score = w_dist * w_wind

        candidates.append({
            "facility_id": fac_ids[i],
            "facility_name": fac_names[i],
            "facility_lat": fac_lats[i],
            "facility_lon": fac_lons[i],
            "distance_km": dist,
            "bearing_deg": bearing if upwind_dir is not None else None,
            "upwind_dir_deg": upwind_dir,
            "angular_offset_deg": theta if upwind_dir is not None else None,
            "w_dist": w_dist,
            "w_wind": w_wind,
            "score": score,
        })

    if candidates:
        # Normalize scores to probabilities
        total_score = sum(c["score"] for c in candidates)
        for c in candidates:
            c["probability"] = c["score"] / total_score if total_score > 0 else 0

        # Sort by score descending
        candidates.sort(key=lambda x: x["score"], reverse=True)

        # Top attribution
        top = candidates[0]
        attribution_results.append({
            "plume_id": plume_id,
            "attributed_facility_id": top["facility_id"],
            "attributed_facility_name": top["facility_name"],
            "attributed_facility_lat": top["facility_lat"],
            "attributed_facility_lon": top["facility_lon"],
            "attribution_probability": top["probability"],
            "attribution_distance_km": top["distance_km"],
            "attribution_angular_offset_deg": top["angular_offset_deg"],
            "attribution_method": "wind_aware",
            "facilities_in_range": len(candidates),
            "second_facility_id": candidates[1]["facility_id"] if len(candidates) > 1 else None,
            "second_facility_probability": candidates[1]["probability"] if len(candidates) > 1 else None,
        })
    else:
        # No facility in range: every attribute of the attribution is NULL, not a sentinel
        # and not 0. Only attribution_method ('no_match') and facilities_in_range (0) carry
        # values, because they are facts about the search rather than about a facility.
        # attributed_facility_name used to be the string "NO_FACILITY_IN_RANGE" and
        # attribution_probability 0.0; both read as real values downstream. 06 took the
        # sentinel as a facility name for gold_emission_sites.
        attribution_results.append({
            "plume_id": plume_id,
            "attributed_facility_id": None,
            "attributed_facility_name": None,
            "attributed_facility_lat": None,
            "attributed_facility_lon": None,
            "attribution_probability": None,
            "attribution_distance_km": None,
            "attribution_angular_offset_deg": None,
            "attribution_method": "no_match",
            "facilities_in_range": 0,
            "second_facility_id": None,
            "second_facility_probability": None,
        })

attribution_df = pd.DataFrame(attribution_results)
print(f"Attribution complete for {len(attribution_df)} plumes")
print(f"Plumes with facility match: {(attribution_df['facilities_in_range'] > 0).sum()}")
print(f"Plumes with no match: {(attribution_df['facilities_in_range'] == 0).sum()}")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ### Attribution quality summary:

# CELL ********************

matched = attribution_df[attribution_df["facilities_in_range"] > 0]

if len(matched) > 0:
    print("=== Attribution Summary ===")
    print(f"Plumes attributed: {len(matched)} / {len(attribution_df)}")
    print()
    print("--- Attribution Probability ---")
    print(f"  Min:    {matched['attribution_probability'].min():.3f}")
    print(f"  Median: {matched['attribution_probability'].median():.3f}")
    print(f"  Mean:   {matched['attribution_probability'].mean():.3f}")
    print(f"  Max:    {matched['attribution_probability'].max():.3f}")
    print()
    print("--- Distance to Attributed Facility ---")
    print(f"  Min:    {matched['attribution_distance_km'].min():.1f} km")
    print(f"  Median: {matched['attribution_distance_km'].median():.1f} km")
    print(f"  Max:    {matched['attribution_distance_km'].max():.1f} km")
    print()
    print("--- Facilities in Range per Plume ---")
    print(matched["facilities_in_range"].describe().to_string())
    print()
    print("--- Top Attributed Facilities ---")
    top_fac = matched.groupby("attributed_facility_name").agg(
        plume_count=("plume_id", "count"),
        avg_probability=("attribution_probability", "mean"),
        avg_distance_km=("attribution_distance_km", "mean"),
    ).sort_values("plume_count", ascending=False)
    print(top_fac.head(15).to_string())
else:
    print("No plumes attributed to any facility")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ### Merge attribution into plume catalog and update Gold table:

# CELL ********************

# Drop any existing attribution columns before merging new ones
attribution_cols = [c for c in plumes.columns if c.startswith("attributed_") 
                    or c.startswith("attribution_") 
                    or c in ["facilities_in_range", "second_facility_id", "second_facility_probability"]]

if attribution_cols:
    print(f"Dropping {len(attribution_cols)} old attribution columns")
    plumes_clean = plumes.drop(columns=attribution_cols)
else:
    plumes_clean = plumes

# Merge fresh attribution
plumes_attributed = plumes_clean.merge(attribution_df, on="plume_id", how="left")

# Verify no duplicate columns
dupes = [c for c in plumes_attributed.columns if c.endswith("_x") or c.endswith("_y")]
if dupes:
    print(f"WARNING: duplicate columns found: {dupes}")
else:
    print("No duplicate columns")

# Write updated gold table -- typed explicitly, never inferred.
#
# A missing value in a pandas object column is float('nan'), and Spark's pandas conversion
# turns that into the STRING "NaN" in a string column. For the 7 no-match plumes this put
# 'NaN' into attributed_facility_id, which passes IS NOT NULL and then fails to join to
# dim_facility; 03c's referential-integrity check caught it. A NaN in a double column is
# just as invisible, since Spark keeps NaN as a value and IS NOT NULL passes it. So the frame
# is built from Python rows against an explicit schema. Every attribution column is typed
# here, and a missing value becomes a real NULL. The catalog's other columns keep the schema
# they were read with.
from pyspark.sql import types as T

ATTRIBUTION_FIELDS = [
    T.StructField("attributed_facility_id", T.StringType()),
    T.StructField("attributed_facility_name", T.StringType()),
    T.StructField("attributed_facility_lat", T.DoubleType()),
    T.StructField("attributed_facility_lon", T.DoubleType()),
    T.StructField("attribution_probability", T.DoubleType()),
    T.StructField("attribution_distance_km", T.DoubleType()),
    T.StructField("attribution_angular_offset_deg", T.DoubleType()),
    T.StructField("attribution_method", T.StringType()),
    T.StructField("facilities_in_range", T.LongType()),
    T.StructField("second_facility_id", T.StringType()),
    T.StructField("second_facility_probability", T.DoubleType()),
]
ATTRIBUTION_COLS = [f.name for f in ATTRIBUTION_FIELDS]
assert set(ATTRIBUTION_COLS) == set(attribution_df.columns) - {"plume_id"}, (
    "attribution_df and ATTRIBUTION_FIELDS disagree: "
    f"{sorted(set(attribution_df.columns) - {'plume_id'} ^ set(ATTRIBUTION_COLS))}")
_base = [f for f in CATALOG_SCHEMA.fields if f.name not in attribution_cols]
OUT_SCHEMA = T.StructType(_base + ATTRIBUTION_FIELDS)
plumes_attributed = plumes_attributed[[f.name for f in OUT_SCHEMA.fields]]


def _cell(v, field, attribution):
    """A value Spark's verifier accepts for this field; a missing value becomes None."""
    missing = v is None or v is pd.NA or v is pd.NaT
    if not missing and isinstance(v, float) and np.isnan(v):
        # NaN is "missing" in a string column always, and in an attribution double too.
        # A catalog double keeps its NaN: 04 wrote it, and this notebook does not reinterpret it.
        missing = attribution or not isinstance(field.dataType, (T.DoubleType, T.FloatType))
    if missing:
        return None
    if isinstance(v, pd.Timestamp):
        return v.to_pydatetime()
    if isinstance(v, np.generic):
        v = v.item()
    if isinstance(field.dataType, T.StringType) and not isinstance(v, str):
        raise TypeError(f"{field.name}: non-string {v!r} ({type(v).__name__}) for a string "
                        "column -- this is how 'NaN' strings get written")
    if isinstance(field.dataType, (T.LongType, T.IntegerType)):
        return int(v)
    if isinstance(field.dataType, (T.DoubleType, T.FloatType)):
        return float(v)
    return v


_is_attr = [f.name in ATTRIBUTION_COLS for f in OUT_SCHEMA.fields]
_rows = [tuple(_cell(v, f, a) for v, f, a in zip(r, OUT_SCHEMA.fields, _is_attr))
         for r in plumes_attributed.itertuples(index=False, name=None)]
plumes_spark = spark.createDataFrame(_rows, OUT_SCHEMA)
plumes_spark.write \
    .format("delta") \
    .mode("overwrite") \
    .option("overwriteSchema", "true") \
    .saveAsTable("gold_plume_catalog")

print(f"Updated gold_plume_catalog with attribution ({len(plumes_attributed)} plumes)")
print(f"Columns ({len(plumes_attributed.columns)}): {list(plumes_attributed.columns)}")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ### Validation: no attribution column holds a null that is not NULL
#
# The string "NaN", "nan", "None" or "null" in a string column, or a NaN in a double column,
# passes an `IS NOT NULL` filter. It is invisible to every null check downstream, and it only
# surfaces when a join fails. So it is asserted directly, on the table as written, along with
# the consistency the no-match path promises.

# CELL ********************

from pyspark.sql import functions as F

_gpc = spark.table("gold_plume_catalog")
_types = {f.name: f.dataType for f in _gpc.schema.fields}
for f in ATTRIBUTION_FIELDS:
    assert f.name in _types, f"gold_plume_catalog lacks {f.name}"
    assert type(_types[f.name]) is type(f.dataType), (
        f"{f.name} is {_types[f.name].simpleString()}, expected {f.dataType.simpleString()}")

NULL_LIKE = ("nan", "none", "null")
_bad = {}
for f in ATTRIBUTION_FIELDS:
    c = F.col(f.name)
    if isinstance(f.dataType, T.StringType):
        n = _gpc.filter(F.lower(F.trim(c)).isin(*NULL_LIKE)).count()
    elif isinstance(f.dataType, T.DoubleType):
        n = _gpc.filter(F.isnan(c)).count()
    else:
        n = 0
    if n:
        _bad[f.name] = n
assert not _bad, (f"attribution column(s) holding a null-like string or NaN instead of NULL: "
                  f"{_bad}. This passes IS NOT NULL and breaks every join downstream.")

_nm = _gpc.filter("attribution_method = 'no_match'")
_n_nm = _nm.count()
assert _n_nm == _gpc.filter("facilities_in_range = 0").count() \
    == _gpc.filter("attributed_facility_id IS NULL").count(), (
    "attribution_method = 'no_match', facilities_in_range = 0 and a NULL attributed_facility_id "
    "must pick out the same plumes")
_leaky = [f.name for f in ATTRIBUTION_FIELDS
          if f.name not in ("attribution_method", "facilities_in_range")
          and _nm.filter(F.col(f.name).isNotNull()).count()]
assert not _leaky, f"no-match plumes carry values in {_leaky}; every attribute must be NULL"
_ids = {r["facility_id"] for r in spark.table("ref_facilities").select("facility_id").collect()}
_att = {r["attributed_facility_id"] for r in
        _gpc.filter("attributed_facility_id IS NOT NULL").select("attributed_facility_id").collect()}
assert _att <= _ids, f"attributed_facility_id not in ref_facilities: {sorted(_att - _ids)[:5]}"
assert _gpc.filter("attribution_probability IS NOT NULL AND "
                   "(attribution_probability <= 0 OR attribution_probability > 1)").count() == 0

print(f"OK  no attribution column holds 'NaN' / 'nan' / 'None' / 'null' or a double NaN "
      f"({len(ATTRIBUTION_FIELDS)} columns checked)")
print(f"OK  {_n_nm} no-match plume(s): facilities_in_range = 0, every attribute NULL")
print(f"OK  every attributed_facility_id resolves to ref_facilities; probabilities in (0, 1]")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
